// Paginakopij, beide talen uit één structuur. Tekst komt van de oude site;
// kapotte embeds zijn verwijderd, de lege Engelse trouwpagina is vertaald
// vanuit het Nederlands, en 17e/18e-eeuw-claims zijn gelijkgetrokken met de
// geschiedenispagina (gesticht 1660, huidige aanzien ±1733).
//
// Bloktypen: h2/h3/p (met [tekst](url)-links), ul, cta, img, hours,
// openhouse, team, gallery, exhibitions, reviews, newsletterarchive,
// vacancies, reports, note.

export const pages = [
  // ============================================================ NL + EN home
  {
    id: 'home', section: 'thuis', menu: null,
    path: { nl: '/nl/', en: '/en/' },
    hero: 'vooraanzicht-zomer',
    title: { nl: 'Huize Frankendael – het laatste buitenhuis van Amsterdam', en: 'Huize Frankendael – the last country estate of Amsterdam' },
    desc: {
      nl: 'Huize Frankendael, het laatste buitenhuis van Amsterdam: rijksmonument, trouwlocatie en huis voor evenementen van 2 tot 300 gasten. Open Huis elke laatste zondag.',
      en: 'Huize Frankendael, the last country estate of Amsterdam: national monument, wedding venue and event house for 2 to 300 guests. Open House every last Sunday.',
    },
    h1: { nl: 'Welkom bij Huize Frankendael', en: 'Welcome to Huize Frankendael' },
    heroFacts: true,
    body: {
      nl: [
        { p: 'Huize Frankendael is het laatste buitenhuis van Amsterdam. Gesticht in 1660, jarenlang particulier bewoond, en sinds 2008 open voor publiek — als trouwlocatie, als plek voor bijeenkomsten en als tentoonstellingszaal.' },
        { p: 'Het huis staat midden in Park Frankendael, met een symmetrische stijltuin achter het huis en de achttiende-eeuwse salons, boardrooms en het koetshuis daarbinnen. In het rechter koetshuis zit [Restaurant Merkelbach](https://restaurantmerkelbach.nl/), zeven dagen per week open.' },
        { gateways: [
          { img: 'cvc-img-1382-low-huizefrankendael', href: '/nl/feestelijk/trouwen/', title: 'Trouwen', text: 'Officiële trouwlocatie: ceremonie in de salons, diner en feest in het koetshuis.', link: 'Trouwen bij Frankendael' },
          { img: 'boardroom-1', href: '/nl/zakelijk/', title: 'Zakelijk', text: 'Vergaderen, trainen en dineren met 2 tot 300 gasten, in acht karakteristieke ruimtes.', link: 'Ruimtes en mogelijkheden' },
          { img: 'frankendael-opening-wild-care-tame-neglect-06-hires', href: '/nl/kunst/', title: 'Kunst', text: 'De Frankendael Foundation programmeert hedendaagse kunst in het rijksmonument.', link: 'Kunst en Foundation' },
        ] },
        { ohband: true },
        { plate: 'luchtfoto-huis-en-tuin', caption: 'De stijltuin achter het huis, in 2003-2004 opnieuw aangelegd naar achttiende-eeuws model.' },
        { feature: {
          label: 'In het koetshuis',
          h2: 'Restaurant Merkelbach',
          p: [
            'Restaurant Merkelbach draagt de naam van stadsbouwmeester Ben Merkelbach, die hier van 1957 tot 2004 met zijn familie woonde. De keuken is nauw verbonden met Slow Food; in de stijltuin, waar het terras staat, beleef je de seizoenen in de stad.',
            'Zeven dagen per week open voor koffie & taart, à-la-cartelunch en borrel. Reserveren gaat via het restaurant zelf.',
          ],
          cta: [
            { label: 'Reserveer een tafel', href: 'https://bookings.zenchef.com/results?rid=371618' },
            { label: 'restaurantmerkelbach.nl', href: 'https://restaurantmerkelbach.nl/', kind: 'ghost' },
          ],
        } },
        { h2: 'Ruim driehonderd jaar geschiedenis' },
        { p: 'Frankendael is de enige overgebleven buitenplaats in de Watergraafsmeer. Izaak Balde gaf het huis omstreeks 1733 zijn huidige aanzien, met rococo-stucwerk binnen en later een classicistische poort van Jacob Otten Husly aan de Middenweg. [Lees de volledige geschiedenis](/nl/over/geschiedenis-huize-frankendael/).' },
        { p: 'Praktische informatie staat bij [contact en openingstijden](/nl/thuis/contact/) en [route & parkeren](/nl/thuis/contact/route-parkeren/). Een indruk van de ruimtes vind je in het [beeldarchief](/nl/fotos/).' },
      ],
      en: [
        { p: 'Huize Frankendael is the last country estate of Amsterdam. Founded in 1660, privately inhabited for many years, and open to the public since 2008 — as a wedding venue, a place for gatherings and an exhibition space.' },
        { p: 'The house stands in the middle of Park Frankendael, with a symmetrical formal garden behind it and eighteenth-century salons, boardrooms and the coach house within. [Restaurant Merkelbach](https://restaurantmerkelbach.nl/) occupies the right coach house, open seven days a week.' },
        { gateways: [
          { img: 'cvc-img-1382-low-huizefrankendael', href: '/en/festivities/wedding/', title: 'Weddings', text: 'Official wedding venue: ceremony in the salons, dinner and party in the coach house.', link: 'Getting married here' },
          { img: 'boardroom-1', href: '/en/business/', title: 'Business', text: 'Meet, train and dine with 2 to 300 guests, in eight characterful rooms.', link: 'Rooms and possibilities' },
          { img: 'frankendael-opening-wild-care-tame-neglect-06-hires', href: '/en/art/', title: 'Art', text: 'The Frankendael Foundation programmes contemporary art in the national monument.', link: 'Art and Foundation' },
        ] },
        { ohband: true },
        { plate: 'luchtfoto-huis-en-tuin', caption: 'The formal garden behind the house, relaid to an eighteenth-century model in 2003-2004.' },
        { feature: {
          label: 'In the coach house',
          h2: 'Restaurant Merkelbach',
          p: [
            'Restaurant Merkelbach carries the name of city architect Ben Merkelbach, who lived here with his family from 1957 to 2004. The kitchen fully endorses Slow Food; in the formal garden, home to the terrace, you experience the seasons within the city.',
            'Open seven days a week for coffee & cake, à la carte lunch and drinks. Reservations are handled by the restaurant itself.',
          ],
          cta: [
            { label: 'Reserve a table', href: 'https://bookings.zenchef.com/results?rid=371618' },
            { label: 'restaurantmerkelbach.nl', href: 'https://restaurantmerkelbach.nl/', kind: 'ghost' },
          ],
        } },
        { h2: 'Three centuries of history' },
        { p: 'Frankendael is the only remaining country estate in the Watergraafsmeer. Izaak Balde gave the house its current appearance around 1733, with rococo stuccowork inside and later a classicist gate by Jacob Otten Husly on the Middenweg. [Read the full history](/en/about/history/).' },
        { p: 'Practical information is under [contact and opening hours](/en/home/contact/) and [route & parking](/en/home/contact/parking-route/). For an impression of the rooms, see the [image archive](/en/photos/).' },
      ],
    },
  },

  // ============================================================ Over / About
  {
    id: 'over', section: 'over', menu: 'over',
    path: { nl: '/nl/over/', en: '/en/about/' },
    hero: 'tuin-bloesem-bar1408',
    title: { nl: 'Over Huize Frankendael', en: 'About Huize Frankendael' },
    desc: {
      nl: 'Het laatste buitenhuis van Amsterdam: 17e-eeuws rijksmonument met salons, koetshuis, boardrooms en stijltuin — open voor natuur, gastronomie en cultuur.',
      en: 'The last country estate of Amsterdam: a 17th-century monument with salons, coach house, boardrooms and formal garden — open for nature, gastronomy and culture.',
    },
    h1: { nl: 'Over Huize Frankendael', en: 'About Huize Frankendael' },
    body: {
      nl: [
        { p: 'Huize Frankendael is het laatste buitenhuis van Amsterdam. Gesticht in de 17e eeuw, werd het huis gebruikt door notabelen om van natuur en vriendschap te genieten.' },
        { p: 'De stad heeft het buitenhuis inmiddels omarmd, maar aan het grote genieten is weinig veranderd. Huis, tuin en keuken staan het gehele jaar dagelijks open voor de combinatie natuur, gastronomie en cultuur.' },
        { h2: 'Restaurant Merkelbach' },
        { p: '[Restaurant Merkelbach](https://restaurantmerkelbach.nl/) draagt de naam van stadsbouwmeester Ben Merkelbach en bevindt zich in het koetshuis van Huize Frankendael. De keuken is nauw verbonden met [Slow Food](https://www.slowfood.com/). In de stijltuin, waar het terras staat, beleef je de seizoenen in de stad. [Reserveren doe je bij Merkelbach](https://bookings.zenchef.com/results?rid=371618).' },
        { h2: 'Partijen en vergaderingen' },
        { p: 'Naast het restaurant heeft Huize Frankendael prachtige ruimtes:' },
        { ul: ['de [salons](/nl/zakelijk/ruimtes/#salons)', 'het [koetshuis](/nl/zakelijk/ruimtes/#koetshuis)', 'de [boardrooms](/nl/zakelijk/ruimtes/#boardroom)'] },
        { p: 'Deze ruimtes zijn beschikbaar voor groepen van 2 tot 300 personen, voor onder meer vergaderingen, condoleances en private dining. Daarnaast is Huize Frankendael een officiële trouwlocatie. De keuken van restaurant Merkelbach verzorgt de culinaire invulling, met bereidingen volgens de Slow Food-filosofie.' },
        { cta: [ { label: 'Zakelijk bij Frankendael', href: '/nl/zakelijk/' }, { label: 'Feestelijk bij Frankendael', href: '/nl/feestelijk/', kind: 'ghost' } ] },
      ],
      en: [
        { p: 'Huize Frankendael is the last remaining country estate within the city of Amsterdam. Founded in the 17th century, the house was used by people of high distinction to enjoy friendship and nature.' },
        { p: 'While the city has since enclosed the estate, the joy remains. House, kitchen and garden are open throughout the year for the combination of nature, gastronomy and art & culture.' },
        { h2: 'Restaurant Merkelbach' },
        { p: '[Restaurant Merkelbach](https://restaurantmerkelbach.nl/) carries the name of former city architect Ben Merkelbach and is located in the coach house of Huize Frankendael. The kitchen fully endorses the [Slow Food philosophy](https://www.slowfood.com/). In the formal garden, home to the terrace, you experience the seasons within the city. [Reserve a table at Merkelbach](https://bookings.zenchef.com/results?rid=371618).' },
        { h2: 'Festivities and meetings' },
        { p: 'Besides the restaurant, Huize Frankendael has beautiful rooms:' },
        { ul: ['the [salons](/en/business/rooms/#salons)', 'the [coach house](/en/business/rooms/#koetshuis)', 'the [boardrooms](/en/business/rooms/#boardroom)'] },
        { p: 'These rooms accommodate groups of 2 to 300 for meetings, memorial gatherings and private dining, among other occasions. Huize Frankendael is also an official wedding venue in Amsterdam. The kitchen of restaurant Merkelbach takes care of the culinary side, prepared according to the Slow Food philosophy.' },
        { cta: [ { label: 'Business at Frankendael', href: '/en/business/' }, { label: 'Festivities at Frankendael', href: '/en/festivities/', kind: 'ghost' } ] },
      ],
    },
  },

  {
    id: 'geschiedenis', section: 'over', menu: 'over',
    path: { nl: '/nl/over/geschiedenis-huize-frankendael/', en: '/en/about/history/' },
    hero: 'gildemeesters',
    title: { nl: 'Geschiedenis van Huize Frankendael', en: 'History of Huize Frankendael' },
    desc: {
      nl: 'Van drooglegging van de Watergraafsmeer tot rijksmonument: de geschiedenis van buitenplaats Frankendael, gesticht in 1660, met stijltuin en hermitage.',
      en: 'From the draining of the Watergraafsmeer to national monument: the history of the Frankendael estate, founded in 1660, with its formal garden and hermitage.',
    },
    h1: { nl: 'Geschiedenis van Huize Frankendael', en: 'History of Huize Frankendael' },
    // NB: de zes afbeeldingen op de oude pagina waren hotlinks naar
    // amsterdam.nl en zijn daar verwijderd (404). Waar we een eigen foto
    // hebben is die geplaatst; de twee historische kaarten zijn vervallen.
    body: {
      nl: [
        { p: 'Frankendael is de enige overgebleven buitenplaats in de Watergraafsmeer. Langs de Middenweg lagen ooit tientallen buitenplaatsen naast elkaar. In de Gouden Eeuw ontwikkelden rijke Amsterdammers tot in de wijde omtrek van de stad gebieden waar buitenplaatsen werden gesticht: ver van de drukte kon de eigenaar zich in kleine kring terugtrekken om te genieten van de natuur, de oogst aan groente en fruit en de rust van het buitenleven. Het historische complex van Frankendael – nu een beschermd rijksmonument – was ooit zo’n buiten de stad gelegen zomerverblijf.' },
        { h2: 'Een buitenplaats in Amsterdam' },
        { p: 'De stichting van het buiten dat wij nu kennen als Frankendael vond waarschijnlijk niet lang na de droogmaking van de Watergraafsmeer (1628-1629) plaats. In 1631 werden de eerste percelen uitgegeven, maar twintig jaar later overstroomde de Meer en moest hij opnieuw worden drooggemalen. Nicolaas van Liebergen stichtte na die tweede drooglegging in 1660 op de hoek van de Middenweg en de Grote Tochtsloot een hofstede: een symmetrisch gebouwd huis met bijpassende tuin met loofwerken en een moestuin. In 1672 kwam de Meer opnieuw blank te staan: op last van de Vroedschap werd de droogmakerij onder water gezet om het naderende Franse leger tegen te houden.' },
        { p: 'Toen Izaak Balde in 1695 eigenaar werd, bestond de hofstede uit een ‘huysinge, bepotinge, beplantinge en verder getimmerte’. Hij gaf de buitenplaats de naam Frankendael, naar het protestantse toevluchtsoord Frankenthal van zijn grootvader in de Palts bij Worms. Hij breidde het landgoed uit en gaf het huis omstreeks 1733 het huidige aanzien: een hoog corps-de-logis met aan weerszijden lagere koetshuizen en stallen. Het huis werd gedecoreerd in Hollandse Lodewijk XV-stijl, met krulwerk, festoenen en rocaillemotieven. Aan de achterzijde ontstond een uitbouw met goed uitzicht op de siertuin, ooit weelderig aangelegd met in vorm gesnoeide struiken, gekleurde schelpen en veelsoortige bloemen.' },
        { img: 'achteraanzicht-huis-2', caption: 'De achtergevel met de uitgebouwde tuinkamer en de stijltuin' },
        { h2: 'Originele elementen in het interieur' },
        { p: 'Hoewel er in de tuin veel veranderde, is in het interieur de achttiende-eeuwse indeling en afwerking met stucwerk en betimmeringen nog grotendeels aanwezig. Op de hoofdverdieping zijn alle oorspronkelijke houten vouwblinden met bijbehorende luikkasten bewaard. De voordeur geeft toegang tot een gang in de middenas van het huis, waarop drie dubbele deuren met spiegelboogvormig lijstwerk uitkomen. De wanden en het plafond zijn wit gestuct en voorzien van ornamenten in Hollandse Lodewijk XIV-stijl; deze verfijning dateert uit de bouwtijd (circa 1733), vermoedelijk in opdracht van Izaak Balde. Aan het uiteinde van de gang ligt de uitgebouwde tuinkamer. In het souterrain is de balklaag in het zicht en bleven een keukenschouw en een vliegenkast uit de tijd van de grote verbouwing bewaard.' },
        { h2: 'Van buitenplaats tot kwekerij' },
        { p: 'Sinds de vroege negentiende eeuw werd Frankendael permanent bewoond. In 1866 werd het huis eigendom van de Koninklijke Nederlandsche Tuinbouw Maatschappij Linnaeus, die het gebruikte als kantoor, eetzaal en boekerij. De gemeente bracht er in 1882 de kantoren en de tuinbouwschool van de Stadskwekerij in onder, waarna het in 1894 werd bestemd tot woning van het hoofd Gemeentebeplantingen.' },
        { h2: 'Sporen van de laatste bewoners' },
        { p: 'In 1957 bood de gemeente Frankendael als ambtswoning aan aan stadsarchitect Ben Merkelbach. Zijn nazaten woonden en werkten tot 2004 in het pand. De sporen van al deze gebruikers geven het huis een extra cultuurhistorische dimensie. Zo herinnert op de hoofdverdieping een wandmozaïek van beeldend kunstenaar en illustrator Noni Lichtveld (dochter van schrijver Albert Helman) aan de laatste bewoningsfase. Het mozaïek zit in de eenvoudige moderne keuken uit 1957, ontworpen door Merkelbach zelf, en toont voorwerpen en figuren uit het huis Keizersgracht 574, waar de familie Merkelbach-Lichtveld tot 1957 woonde.' },
        { h2: 'Beelden en poort' },
        { p: 'De huidige aanleg van tuin en park laat verschillende fasen van gebruik zien. Waarschijnlijk onder Izaak Balde ontstond de rechthoekige, door boomsingels omgrachte huisplaats. In 1770 werd aan de voorzijde de marmeren beeldengroep met stroomgoden Neptunus, Amphitrite en Arion met schelpvormig bassin geplaatst, gesigneerd ‘I(gnatius) van Logteren, 1714’ en afkomstig van buitenplaats Driemond bij Weesp. Op het voorterrein staan vier beelden van omstreeks 1700, waarschijnlijk geplaatst door Jan Gildemeester, eigenaar vanaf 1759: Ceres met korenschoof, Bacchus met een bokaal druiven, Koning David met kroon en harp, en een jongenskop die vermoedelijk als voetstuk van een vaas diende.' },
        { p: 'In 1783 kwam de classicistische houten poort naar ontwerp van Jacob Otten Husly (1738-1796), architect van Felix Meritis, in opdracht van Jan Gildemeester Janszoon. Zijn wapen — een gebogen, geharnaste arm met een doodsbeen in de hand — is aan de achterzijde van de poort aangebracht, net als in het middenpaneel van de dakbalustrade van het huis.' },
        { h2: 'Hermitage' },
        { p: 'Eigenaar Anthony Dull, de eerste die Frankendael permanent bewoonde, voegde begin negentiende eeuw de bakstenen hermitage of kluizenaarshut toe, met een geconstrueerd landschap langs een waterpartij. Zo’n hermitage was een geliefd object in een landschappelijk aangelegde tuin — tegenwoordig bekend als ‘folly’, maar destijds serieus bedoeld: een plek om je in de natuur te wanen en gedachten de vrije loop te laten.' },
        { h2: 'Van theetuin tot kwekerij' },
        { p: 'Vanaf 1835 werd het park gedeeltelijk opengesteld voor ‘het beschaafde publiek’ en groeide Frankendael uit tot een geliefde plezier- en theetuin. De theetuin sloot in 1866, toen de Koninklijke Nederlandsche Tuinbouw Maatschappij Linnaeus het park als boomkwekerij inrichtte; in 1882 werd het terrein Stadskwekerij. In de Tweede Wereldoorlog werden op Frankendael bouwfragmenten opgeslagen, onder meer van de Nieuwezijdskapel en van de gevel ‘Het Moortje’ aan de Herengracht 126.' },
        { h2: 'Tuin en park nu' },
        { p: 'Van de vier lindensingels rond de huisplaats bleven grote delen intact. Vanaf de late achttiende eeuw ontstond in fasen een landschappelijke aanleg met grillige wandelpaden en heuvelpartijen; een deel werd later heemtuin. Begin deze eeuw gaf stadsdeel Oost/Watergraafsmeer Frankendael weer een openbare functie: in 2003-2004 werd de huisplaats opgeschoond en verrees achter het huis een quasi achttiende-eeuwse symmetrische tuin met bloemperken, lage buxushagen en parterres.' },
        { p: 'Bij graafwerkzaamheden in augustus 2003 stuitte men achter het koetshuis op muurwerk: de resten van een achttiende-eeuwse plantenkas of oranjerie, rond 1820-1830 gesloopt. Een foto uit 1873 toont het gebouwtje als ‘Frankendael theekoepel (voormalige Oranjerie)’, en op een plattegrond uit 1883 is het herkenbaar als volière aan de noordzijde van het landgoed. Na het archeologisch onderzoek zijn de resten opnieuw onder de groene zoden verdwenen.' },
        { img: 'luchtfoto-huis-en-tuin', caption: 'Huize Frankendael en de stijltuin van boven' },
        { h2: 'Literatuur' },
        { ul: [
          'J.T.P. Bijhouwer, Nederlandsche tuinen en buitenplaatsen, Amsterdam 1942, p. 122-124',
          'A. Duisenberg, J. Otten Husly (1738-1796). Avant-garde architect tijdens de Verlichting [BONAS], Rotterdam 1998, p. 95',
          'P.M. Fischer, Ignatius en Jan van Logteren. Beeldhouwers en stuckunstenaars in het Amsterdam van de 18de eeuw, Alphen aan den Rijn 2005',
          'A. Hendriksen, Watergraafsmeer, binnenzee, polder, lustoord, stadsdeel, Amsterdam 1998',
          'B. Rebel e.a., Ben Merkelbach. Architect en stadsbouwmeester, Amsterdam 1994',
          'Open Monumentendag Amsterdam 2003',
        ] },
      ],
      en: [
        { p: 'Frankendael is the only remaining country estate in the Watergraafsmeer. Dozens of estates once lined the Middenweg. During the Dutch Golden Age, wealthy Amsterdammers developed areas well beyond the city where country estates were founded: far from the bustle, an owner could withdraw with close company to enjoy nature, the harvest of fruit and vegetables, and the quiet of country life. The historic Frankendael complex — now a protected national monument — was once such a summer residence outside the city.' },
        { h2: 'A country estate in Amsterdam' },
        { p: 'The estate we now know as Frankendael was probably founded not long after the draining of the Watergraafsmeer (1628-1629). The first plots were issued in 1631, but twenty years later the lake flooded and had to be drained again. After that second reclamation, Nicolaas van Liebergen founded a homestead in 1660 on the corner of the Middenweg and the Grote Tochtsloot: a symmetrically built house with a matching ornamental and kitchen garden. In 1672 the polder was deliberately flooded once more, on the orders of the city council, to hold off the approaching French army.' },
        { p: 'When Izaak Balde became the owner in 1695, the homestead consisted of “huysinge, bepotinge, beplantinge en verder getimmerte” — house, plantings and outbuildings. He named the estate Frankendael, after Frankenthal, the Protestant refuge of his grandfather in the Palatinate near Worms. He extended the grounds and around 1733 gave the house its current appearance: a tall corps de logis flanked by lower coach houses and stables, decorated in the Dutch Louis XV style with scrollwork, festoons and rocaille motifs. At the rear an extension was added with a fine view over the ornamental garden, once lavishly laid out with topiary, coloured shells and a great variety of flowers.' },
        { img: 'achteraanzicht-huis-2', caption: 'The rear façade with the protruding garden room and the formal garden' },
        { h2: 'Original interior elements' },
        { p: 'While the garden changed a great deal, the eighteenth-century layout and finishes — stucco and panelling — largely survive inside. On the main floor all the original wooden folding shutters and their casings remain. The front door opens onto a hallway on the central axis of the house, onto which three double doors with arched mouldings open. Walls and ceiling are white stucco with ornaments in the Dutch Louis XIV style; this refinement dates from the time of construction (circa 1733), presumably commissioned by Izaak Balde. At the end of the hallway lies the protruding garden room. In the basement the joists are exposed, and a kitchen hearth and fly cupboard from Balde’s great rebuilding survive.' },
        { h2: 'From estate to nursery' },
        { p: 'From the early nineteenth century Frankendael was permanently inhabited. In 1866 the house became the property of the Royal Dutch Horticultural Society Linnaeus, which used it as offices, dining hall and library. In 1882 the municipality housed the offices and horticultural school of the City Nursery here, and in 1894 it became the residence of the head of Municipal Plantings.' },
        { h2: 'Traces of the last residents' },
        { p: 'In 1957 the municipality offered Frankendael as an official residence to city architect Ben Merkelbach. His descendants lived and worked in the building until 2004. The traces of all these successive users give the house an extra cultural-historical dimension: on the main floor, a wall mosaic designed by visual artist and illustrator Noni Lichtveld (daughter of the writer Albert Helman) recalls the final period of habitation. The mosaic sits in the simple modern kitchen of 1957, designed by Merkelbach himself, and depicts objects and figures from Keizersgracht 574, where the Merkelbach-Lichtveld family lived until 1957.' },
        { h2: 'Sculptures and gate' },
        { p: 'The current layout of garden and park shows several phases of use. The rectangular house plot, moated and ringed by tree belts, probably took shape under Izaak Balde. In 1770 the marble sculpture group of the river gods Neptune, Amphitrite and Arion with its shell-shaped basin was placed at the front, signed “I(gnatius) van Logteren, 1714” and originating from the Driemond estate near Weesp. On the forecourt stand four sculptures from around 1700, probably placed by Jan Gildemeester, owner from 1759: Ceres with a sheaf of corn, Bacchus with a goblet of grapes, King David with crown and harp, and a boy’s head that presumably served as the base of a vase.' },
        { p: 'In 1783 the classicist wooden gate was erected to a design by Jacob Otten Husly (1738-1796), architect of Felix Meritis, commissioned by Jan Gildemeester Janszoon. His coat of arms — a bent, armoured arm holding a bone — appears on the back of the gate, as it does in the centre panel of the roof balustrade of the house itself.' },
        { h2: 'Hermitage' },
        { p: 'Anthony Dull, the first owner to live at Frankendael permanently, added the brick hermitage in the early nineteenth century, set in a constructed landscape along a winding waterway. Such a hermitage was a beloved feature of landscape gardens — now called a “folly”, but meant sincerely at the time: a place to imagine yourself in nature and let your thoughts wander.' },
        { h2: 'From tea garden to nursery' },
        { p: 'From 1835 the park was partly opened to “the civilised public” and Frankendael quickly grew into a much-loved pleasure and tea garden. The tea garden closed in 1866, when the Linnaeus society turned the park into a tree nursery; in 1882 the grounds became the City Nursery. During the Second World War architectural fragments were stored at Frankendael, including pieces of the Nieuwezijds Chapel and of the façade “Het Moortje” at Herengracht 126.' },
        { h2: 'Garden and park today' },
        { p: 'Large parts of the four lime-tree belts around the house plot remain intact. From the late eighteenth century a landscape layout with winding paths and hillocks emerged in phases; part of it later became a botanical instruction garden. At the start of this century the Oost/Watergraafsmeer district returned Frankendael to public use: in 2003-2004 the house plot was restored and a quasi-eighteenth-century symmetrical garden with flower beds, low box hedges and parterres was laid out behind the house.' },
        { p: 'During excavation work in August 2003, masonry was discovered behind the coach house: the remains of an eighteenth-century greenhouse or orangery, demolished around 1820-1830. A photograph from 1873 shows the building as “Frankendael tea dome (former Orangery)”, and on an 1883 map it is recognisable as an aviary on the north side of the estate. After the archaeological research the remains disappeared under the turf once more.' },
        { img: 'luchtfoto-huis-en-tuin', caption: 'Huize Frankendael and the formal garden from above' },
        { h2: 'Literature' },
        { ul: [
          'J.T.P. Bijhouwer, Nederlandsche tuinen en buitenplaatsen, Amsterdam 1942, p. 122-124',
          'A. Duisenberg, J. Otten Husly (1738-1796). Avant-garde architect tijdens de Verlichting [BONAS], Rotterdam 1998, p. 95',
          'P.M. Fischer, Ignatius en Jan van Logteren. Beeldhouwers en stuckunstenaars in het Amsterdam van de 18de eeuw, Alphen aan den Rijn 2005',
          'A. Hendriksen, Watergraafsmeer, binnenzee, polder, lustoord, stadsdeel, Amsterdam 1998',
          'B. Rebel e.a., Ben Merkelbach. Architect en stadsbouwmeester, Amsterdam 1994',
          'Open Monumentendag Amsterdam 2003',
        ] },
      ],
    },
  },

  {
    id: 'team', section: 'over', menu: 'over',
    path: { nl: '/nl/over/ons-team/', en: '/en/home/contact/our-team/' },
    hero: 'kunst-algemeen',
    title: { nl: 'Ons team – Huize Frankendael', en: 'Our team – Huize Frankendael' },
    desc: {
      nl: 'Het team van Huize Frankendael en Restaurant Merkelbach: directie, keuken, events en banqueting — met directe contactgegevens.',
      en: 'The team of Huize Frankendael and Restaurant Merkelbach: management, kitchen, events and banqueting — with direct contact details.',
    },
    h1: { nl: 'Ons team', en: 'Our team' },
    body: {
      nl: [
        { p: 'Huize Frankendael en Restaurant Merkelbach werken met één team. Voor vragen en opmerkingen staan wij open — neem gerust contact op.' },
        { team: true },
        { p: 'Algemene vragen: [info@huizefrankendael.nl](mailto:info@huizefrankendael.nl) of [020 – 423 39 30](tel:+31204233930) (ma t/m vr 9.00–17.00 uur).' },
      ],
      en: [
        { p: 'Huize Frankendael and Restaurant Merkelbach work as one team. Questions and remarks are welcome — do get in touch.' },
        { team: true },
        { p: 'General enquiries: [info@huizefrankendael.nl](mailto:info@huizefrankendael.nl) or [+31 20 423 39 30](tel:+31204233930) (Mon–Fri 9 AM–5 PM).' },
      ],
    },
  },

  {
    id: 'werken', section: 'over', menu: 'over',
    path: { nl: '/nl/over/werken-bij-huize-frankendael/', en: '/en/home/contact/working-at-huize-frankendael/' },
    hero: 'koetshuis-diner-4',
    title: { nl: 'Werken bij Huize Frankendael', en: 'Working at Huize Frankendael' },
    desc: {
      nl: 'Vacatures bij Huize Frankendael en Restaurant Merkelbach: keuken, bediening en eventmanagement, midden in Park Frankendael.',
      en: 'Vacancies at Huize Frankendael and Restaurant Merkelbach: kitchen, service and event management, in the middle of Park Frankendael.',
    },
    h1: { nl: 'Werken bij Huize Frankendael', en: 'Working at Huize Frankendael' },
    body: {
      nl: [
        { p: 'Huize Frankendael en [Restaurant Merkelbach](https://restaurantmerkelbach.nl/) zoeken regelmatig versterking, van keuken tot bediening en events. Hieronder staan de rollen zoals wij die zoeken; mail gerust om te vragen wat er op dit moment openstaat.' },
        { vacancies: true },
        { note: 'Niets voor jou bij, wel enthousiast? Stuur een open sollicitatie naar [info@huizefrankendael.nl](mailto:info@huizefrankendael.nl).' },
      ],
      en: [
        { p: 'Huize Frankendael and [Restaurant Merkelbach](https://restaurantmerkelbach.nl/) regularly look for new colleagues, from kitchen to service and events. Below are the roles we recruit for; feel free to email and ask what is currently open.' },
        { vacancies: true },
        { note: 'Nothing that fits, but enthusiastic anyway? Send an open application to [info@huizefrankendael.nl](mailto:info@huizefrankendael.nl).' },
      ],
    },
  },

  // ============================================================ Zakelijk / Business
  {
    id: 'zakelijk', section: 'zakelijk', menu: 'zakelijk',
    path: { nl: '/nl/zakelijk/', en: '/en/business/' },
    hero: 'boardroom-1',
    title: { nl: 'Zakelijke bijeenkomsten – Huize Frankendael', en: 'Business events – Huize Frankendael' },
    desc: {
      nl: 'Vergaderen, trainen of dineren met 2 tot 300 personen in de salons, boardroom of het koetshuis van Huize Frankendael. Gratis wifi en Slow Food-catering.',
      en: 'Meet, train or dine with 2 to 300 people in the 18th-century salons, boardroom or coach house of Huize Frankendael. Free wifi and Slow Food catering.',
    },
    h1: { nl: 'Zakelijk bij Huize Frankendael', en: 'Business at Huize Frankendael' },
    body: {
      nl: [
        { p: 'Huize Frankendael staat open voor zakelijke bijeenkomsten van 2 tot 300 personen. De 18e-eeuwse [salons](/nl/zakelijk/ruimtes/#salons) en 19e-eeuwse kamers in het huis vormen een statige plek voor een besloten diner, training, netwerkevent of vergadering. Ook het [koetshuis](/nl/zakelijk/ruimtes/#koetshuis) is een inspirerende setting voor workshops en heidagen. Met mooi weer zorgt de stijltuin voor een ontspannen omgeving tijdens pauzes en break-outsessies.' },
        { h2: 'Maatwerk' },
        { p: 'Huize Frankendael levert graag maatwerk. We luisteren naar je wensen en het team zorgt dat je je thuis voelt. Alle vertrekken hebben gratis wifi; beamers, schermen en flip-overs staan in overleg voor je klaar. De nabijheid van de ring A10 en ruime [parkeergelegenheid](/nl/thuis/contact/route-parkeren/) (uitrijkaarten voor de parkeergarage beschikbaar) maken dit een praktische plek voor zakelijke gasten.' },
        { h2: 'Slow Food-gastronomie' },
        { p: '[Restaurant Merkelbach](https://restaurantmerkelbach.nl/) serveert in elke ruimte ontbijt, lunch, borrel of diner op topniveau, volgens de Slow Food-filosofie van de keuken.' },
        { cta: [ { label: 'Bekijk de ruimtes', href: '/nl/zakelijk/ruimtes/' }, { label: 'Mail voor een offerte', href: 'mailto:info@huizefrankendael.nl?subject=Zakelijke%20aanvraag', kind: 'ghost' } ] },
      ],
      en: [
        { p: 'Huize Frankendael caters for business events of 2 to 300 people. The 18th-century [salons](/en/business/rooms/#salons) and 19th-century rooms in the house provide a stately backdrop for a private dinner, training session, network event or meeting. The [coach house](/en/business/rooms/#koetshuis) is another inspirational setting for workshops and off-site days. In good weather, the formal garden offers a relaxed environment for breaks and break-out sessions.' },
        { h2: 'Tailor-made' },
        { p: 'We are on hand to discuss your needs personally, and our team makes sure you feel at home. All rooms have free wifi; projectors, screens and flip charts can be set up on request. The proximity of the A10 ring road and ample [parking](/en/home/contact/parking-route/) (exit tickets for the nearby car park available) make this a practical venue for business guests.' },
        { h2: 'Slow Food gastronomy' },
        { p: '[Restaurant Merkelbach](https://restaurantmerkelbach.nl/) serves high-quality breakfast, lunch, drinks or dinner in every room, according to the kitchen’s Slow Food philosophy.' },
        { cta: [ { label: 'See the rooms', href: '/en/business/rooms/' }, { label: 'Email for a proposal', href: 'mailto:info@huizefrankendael.nl?subject=Business%20enquiry', kind: 'ghost' } ] },
      ],
    },
  },

  {
    id: 'zakelijk-ruimtes', section: 'zakelijk', menu: 'zakelijk',
    path: { nl: '/nl/zakelijk/ruimtes/', en: '/en/business/rooms/' },
    hero: 'frankendael-foundation-amsterdam-reyn-van-der-lugt-collection-4749',
    title: { nl: 'Zakelijke ruimtes – Huize Frankendael', en: 'Business rooms – Huize Frankendael' },
    desc: {
      nl: 'De boardroom, salons, tuinkamer en het koetshuis van Huize Frankendael: vier karakteristieke ruimtes voor vergaderingen, trainingen en besloten diners.',
      en: 'The boardroom, salons, garden room and coach house of Huize Frankendael: four characterful rooms for meetings, training sessions and private dinners.',
    },
    h1: { nl: 'Ruimtes', en: 'Rooms' },
    body: {
      nl: [
        { h2: 'Boardroom', anchor: 'boardroom' },
        { p: 'De boardroom op de tweede verdieping is modern ingericht en uitermate geschikt als vergaderruimte. De kamer kijkt aan de ene kant uit over de klassieke stijltuin en aan de andere kant over de stad. Een groot projectiescherm is in de ruimte geïntegreerd, en op dezelfde verdieping liggen twee break-outruimtes. In de boardroom hangt steeds wisselende hedendaagse kunst.' },
        { img: 'boardroom-1' },
        { h2: 'Salons', anchor: 'salons' },
        { p: 'De salons op de bel-etage geven uitzicht op de omringende tuinen. De grote salon heeft een haard die afkomstig is uit de burgemeesterswoning, en het plafond draagt het vroegste rococostucwerk van Nederland. De salons bieden een voornaam én sfeervol decor voor bijeenkomsten die bijzonder mogen heten — van vergadering tot privédiner.' },
        { img: 'grote-salon-gedekte-tafels-bar9418' },
        { h2: 'Tuinkamer', anchor: 'tuinkamer' },
        { p: 'De tuinkamer op de bel-etage is in de 18e eeuw aangebouwd en kijkt via drie ramen rondom uit over de stijltuin. Een unieke en inspirerende ruimte voor een besloten vergadering of diner, en een geliefde break-outruimte.' },
        { img: 'tuinkamer-met-uitzicht' },
        { h2: 'Koetshuis', anchor: 'koetshuis' },
        { p: 'Het koetshuis lijkt nog het meest op een sfeervolle boerenstal midden in de stad. De mogelijkheden zijn talrijk: met een mobiele bar kun je binnen én buiten terecht, en het te overdekken terras naast het koetshuis hoort exclusief bij de ruimte.' },
        { img: 'koetshuis-22' },
        { cta: [ { label: 'Alle foto’s', href: '/nl/fotos/' }, { label: 'Mail voor beschikbaarheid', href: 'mailto:info@huizefrankendael.nl?subject=Beschikbaarheid%20ruimtes', kind: 'ghost' } ] },
      ],
      en: [
        { h2: 'Boardroom', anchor: 'boardroom' },
        { p: 'The contemporary boardroom on the second floor is perfectly suited to meetings. It looks out over the classical formal garden on one side and the cityscape on the other. A large projection screen is an integral feature, and two break-out rooms sit on the same floor. Ever-changing contemporary art hangs in the boardroom.' },
        { img: 'boardroom-1' },
        { h2: 'Salons', anchor: 'salons' },
        { p: 'The salons on the first floor look out over the surrounding gardens. The fireplace in the grand salon was originally located in the mayoral residence, and the ceiling carries the earliest rococo stuccowork in the Netherlands. The grand, striking salons are truly exceptional venues — from meetings to private dinners.' },
        { img: 'grote-salon-gedekte-tafels-bar9418' },
        { h2: 'Garden room', anchor: 'tuinkamer' },
        { p: 'The garden room on the first floor was added in the 18th century and looks out over the formal garden through windows on three sides. A unique and inspirational space for a private meeting or dinner, and a favourite break-out room.' },
        { img: 'tuinkamer-met-uitzicht' },
        { h2: 'Coach house', anchor: 'koetshuis' },
        { p: 'The coach house most resembles an atmospheric farmstead in the middle of the city. The possibilities are endless: a mobile bar allows for events both in and outdoors, and the coverable patio next to the coach house belongs exclusively to the space.' },
        { img: 'koetshuis-22' },
        { cta: [ { label: 'All photos', href: '/en/photos/' }, { label: 'Email for availability', href: 'mailto:info@huizefrankendael.nl?subject=Room%20availability', kind: 'ghost' } ] },
      ],
    },
  },

  // ============================================================ Feestelijk / Festivities
  {
    id: 'feestelijk', section: 'feestelijk', menu: 'feestelijk',
    path: { nl: '/nl/feestelijk/', en: '/en/festivities/' },
    hero: 'bruiloft-carienkrijn-305-web',
    title: { nl: 'Feestelijke evenementen – Huize Frankendael', en: 'Festivities – Huize Frankendael' },
    desc: {
      nl: 'Vier je verjaardag, diner of feest met 10 tot 300 gasten in de salons, het koetshuis of de stijltuin van Huize Frankendael — met catering van Restaurant Merkelbach.',
      en: 'Celebrate a birthday, dinner or party with 10 to 300 guests in the salons, coach house or formal garden of Huize Frankendael — catered by Restaurant Merkelbach.',
    },
    h1: { nl: 'Feestelijk', en: 'Festivities' },
    body: {
      nl: [
        { h2: 'Unieke locatie' },
        { p: 'Huize Frankendael is als laatste buitenplaats van Amsterdam één van de topmonumenten van de stad. Niet alleen de geschiedenis spreekt tot de verbeelding: vandaag de dag vier je hier je verjaardag, organiseer je een diner of trouw je er. Alle [salons, kamers en vertrekken](/nl/feestelijk/ruimtes/) in het hele huis staan voor je open, voor feesten van 10 tot 300 personen.' },
        { h2: 'Private dining' },
        { p: 'De kamers bieden een unieke achtergrond voor een privédiner, verzorgd door de keuken van [Restaurant Merkelbach](https://restaurantmerkelbach.nl/). Zowel een sit-down dinner als een walking dinner behoort tot de mogelijkheden.' },
        { h2: 'Feesten en borrels' },
        { p: 'Voor verjaardagen of promotiefeesten kun je zowel in de salons als in het [koetshuis](/nl/feestelijk/ruimtes/#koetshuis) terecht. In het koetshuis organiseren wij uitgebreide borrels of feesten met een dj. Geniet zorgeloos van onvergetelijke momenten in één van de ruimtes.' },
        { h2: 'Trouwen' },
        { p: 'Huize Frankendael is een officiële trouwlocatie. Bruiloften worden van begin tot eind in huis gevierd en het team neemt alle zorgen uit handen. De combinatie van binnen en buiten maakt dit een unieke plek in Amsterdam. Lees meer over [trouwen bij Huize Frankendael](/nl/feestelijk/trouwen/).' },
        { h2: 'Duizend-en-één mogelijkheden' },
        { p: 'Een opera in de tuin, een diner voor 300 gasten voor het huis of een Hollandse Nieuwe-haringpartij? De mogelijkheden zijn talrijk op Huize Frankendael. Wij omarmen ieder idee, hoe ludiek ook.' },
        { h2: 'Persoonlijk' },
        { p: 'Ieder feest is persoonlijk. Daarom nemen wij je wensen graag onder het genot van een kop koffie met je door.' },
        { cta: [ { label: 'Mail voor een afspraak', href: 'mailto:info@huizefrankendael.nl?subject=Feestelijke%20aanvraag' }, { label: 'Bekijk de ruimtes', href: '/nl/feestelijk/ruimtes/', kind: 'ghost' } ] },
      ],
      en: [
        { h2: 'Unique location' },
        { p: 'As the last remaining country estate in Amsterdam, Huize Frankendael is one of the city’s top monuments. Its appeal goes far beyond its history: today you can celebrate your birthday, organise a dinner or get married here. All the [salons and rooms](/en/festivities/rooms/) throughout the house are open to you, for festivities of 10 to 300 people.' },
        { h2: 'Private dining' },
        { p: 'The rooms provide a unique backdrop for a private dinner, catered by the kitchen of [Restaurant Merkelbach](https://restaurantmerkelbach.nl/). Both a sit-down dinner and a walking dinner are possible.' },
        { h2: 'Parties and receptions' },
        { p: 'For birthdays or celebration parties you can use both the salons and the [coach house](/en/festivities/rooms/#koetshuis), where we organise extensive receptions and parties with a DJ. Enjoy unforgettable moments in one of the rooms, carefree.' },
        { h2: 'Weddings' },
        { p: 'Huize Frankendael is an official wedding venue. Weddings are celebrated in-house from beginning to end, and our team takes every care off your hands. The combination of indoors and outdoors makes this a unique place in Amsterdam. Read more about [getting married at Huize Frankendael](/en/festivities/wedding/).' },
        { h2: 'A thousand and one possibilities' },
        { p: 'A garden opera, a dinner for 300 in view of the house, or a “Hollandse Nieuwe” herring party? The possibilities at Huize Frankendael are endless; we embrace every idea, however playful.' },
        { h2: 'Personal' },
        { p: 'Every party is personal, which is why we like to discuss your wishes over a cup of coffee.' },
        { cta: [ { label: 'Email for an appointment', href: 'mailto:info@huizefrankendael.nl?subject=Festive%20enquiry' }, { label: 'See the rooms', href: '/en/festivities/rooms/', kind: 'ghost' } ] },
      ],
    },
  },

  {
    id: 'trouwen', section: 'feestelijk', menu: 'feestelijk',
    path: { nl: '/nl/feestelijk/trouwen/', en: '/en/festivities/wedding/' },
    hero: 'cvc-img-1382-low-huizefrankendael',
    title: { nl: 'Trouwen bij Huize Frankendael', en: 'Getting married at Huize Frankendael' },
    desc: {
      nl: 'Officiële trouwlocatie in Amsterdam: ceremonie in de 18e-eeuwse salons en tuin, diner en feest in het koetshuis, catering door Restaurant Merkelbach.',
      en: 'Official wedding venue in Amsterdam: ceremony in the 18th-century salons and garden, dinner and party in the coach house, catering by Merkelbach.',
    },
    h1: { nl: 'Trouwen bij Huize Frankendael', en: 'Getting married at Huize Frankendael' },
    body: {
      nl: [
        { p: 'Huize Frankendael is een officiële trouwlocatie: een unieke buitenplaats met park en stijltuinen, midden in Amsterdam.' },
        { p: 'Je gehele huwelijksdag kan bij ons plaatsvinden. De ceremonie met aansluitende receptie vindt plaats in de 18e-eeuwse salons en de tuin; het diner met aansluitend feest organiseer je in het rustieke koetshuis. Bij mooi weer serveren wij het diner ook buiten in de tuin.' },
        { img: 'bruiloft-carienkrijn-305-web', caption: 'Bruiloftsdiner in de tuin' },
        { h2: 'Slow Food-gastronomie' },
        { p: 'De catering voor je huwelijksdag wordt verzorgd door [restaurant Merkelbach](https://restaurantmerkelbach.nl/). De filosofie van de keuken sluit aan bij het statige historische buiten: authentieke smaak en de Slow Food-filosofie staan centraal.' },
        { h2: 'Persoonlijk contact' },
        { p: 'Wij maken offertes op maat en nodigen je graag uit voor een rondleiding en een persoonlijk gesprek, waarin we alle mogelijkheden toelichten. Wij denken met plezier mee over de samenstelling van jullie trouwdag!' },
        { cta: [ { label: 'Mail voor een rondleiding', href: 'mailto:info@huizefrankendael.nl?subject=Trouwen%20bij%20Huize%20Frankendael' }, { label: 'Bel 020 – 423 39 30', href: 'tel:+31204233930', kind: 'ghost' } ] },
        { p: 'Bekijk ook de [foto-impressie van trouwen bij Huize Frankendael](/nl/fotos/#g-trouwen).' },
        { h2: 'Bruidsfotografie' },
        { p: 'Het is niet mogelijk het huis enkel voor bruidsfotografie te reserveren, en trouwfoto’s maken kan alleen als je huwelijk bij ons plaatsvindt. Op je eigen trouwdag ben je uiteraard vrij om in en rond het huis bruidsfoto’s te maken.' },
      ],
      en: [
        { p: 'Huize Frankendael is an official wedding venue: a unique country estate with a park and formal gardens, in the middle of Amsterdam.' },
        { p: 'Your entire wedding day can take place with us. The ceremony and reception are held in the 18th-century salons and the garden; dinner and the party that follows take place in the rustic coach house. In good weather we also serve dinner outside in the garden.' },
        { img: 'bruiloft-carienkrijn-305-web', caption: 'Wedding dinner in the garden' },
        { h2: 'Slow Food gastronomy' },
        { p: 'The catering for your wedding day is provided by [restaurant Merkelbach](https://restaurantmerkelbach.nl/). The kitchen’s philosophy matches the stately, historic estate: authentic flavour and Slow Food values are central.' },
        { h2: 'Personal contact' },
        { p: 'We prepare tailor-made proposals and gladly invite you for a tour and a personal conversation to walk you through the possibilities. We love thinking along about the shape of your wedding day!' },
        { cta: [ { label: 'Email for a tour', href: 'mailto:info@huizefrankendael.nl?subject=Wedding%20at%20Huize%20Frankendael' }, { label: 'Call +31 20 423 39 30', href: 'tel:+31204233930', kind: 'ghost' } ] },
        { p: 'Also see the [photo impression of weddings at Huize Frankendael](/en/photos/#g-trouwen).' },
        { h2: 'Wedding photography' },
        { p: 'It is not possible to reserve the house for bridal photography alone, and wedding photos can only be taken if your wedding takes place with us. On your own wedding day you are of course free to take photos in and around the house.' },
      ],
    },
  },

  {
    id: 'feest-ruimtes', section: 'feestelijk', menu: 'feestelijk',
    path: { nl: '/nl/feestelijk/ruimtes/', en: '/en/festivities/rooms/' },
    hero: 'koetshuis-disco-licht-melissamilis',
    title: { nl: 'Feestelijke ruimtes – Huize Frankendael', en: 'Festive rooms – Huize Frankendael' },
    desc: {
      nl: 'De salons, het koetshuis en de stijltuin van Huize Frankendael: drie sfeervolle plekken voor bruiloften, diners en feesten.',
      en: 'The salons, coach house and formal garden of Huize Frankendael: three atmospheric settings for weddings, dinners and parties.',
    },
    h1: { nl: 'Ruimtes', en: 'Rooms' },
    body: {
      nl: [
        { h2: 'Salons', anchor: 'salons' },
        { p: 'De salons zijn het populairst. De goudkleurige wandbespanning en de marmeren gangen maken grootse indruk; niet voor niets is de grote salon onze trouwzaal. Op het bordes voor het huis zijn al vele ceremoniële en familieportretten gemaakt.' },
        { img: 'salon-trouwopstelling' },
        { h2: 'Koetshuis', anchor: 'koetshuis' },
        { p: 'Het koetshuis wordt vaak het sfeervolste deel van het huis genoemd. De drinkbakken verraden waar vroeger de paarden stonden. Met eigen bar en buffet past het koetshuis zich aan elke wens aan: in zijn geheel of in tweeën gedeeld, en mét eigen patio onder de magnoliaboom. Feesten en recepties vinden hier geregeld plaats.' },
        { img: 'zomerdiner-koetshuis-joostweddepohl' },
        { h2: 'Stijltuin', anchor: 'stijltuin' },
        { p: 'De stijltuin is in elk seizoen mooi, maar in de zomer toont de tuin zich in overvloedig groen. De kamers van het huis lopen naadloos over in het rustgevende groen van de tuin.' },
        { img: 'tuin-bar1402' },
        { cta: [ { label: 'Alle foto’s', href: '/nl/fotos/' }, { label: 'Mail voor beschikbaarheid', href: 'mailto:info@huizefrankendael.nl?subject=Beschikbaarheid%20feestruimtes', kind: 'ghost' } ] },
      ],
      en: [
        { h2: 'Salons', anchor: 'salons' },
        { p: 'Our salons are the most popular. The golden wall coverings and marble hallways evoke grand impressions; the reason the grand salon is our wedding room is plain to see. Many ceremonial and family portraits have been taken on the front steps of the house.' },
        { img: 'salon-trouwopstelling' },
        { h2: 'Coach house', anchor: 'koetshuis' },
        { p: 'The coach house is often regarded as the most atmospheric part of the house. The drinking troughs show where the horses once stood. With its own bar and buffet it can match every request: used as a whole or divided in two, with its private patio under the magnolia tree. Parties and receptions are regularly held here.' },
        { img: 'zomerdiner-koetshuis-joostweddepohl' },
        { h2: 'Formal garden', anchor: 'stijltuin' },
        { p: 'The formal garden is beautiful in every season, but in summer it shows itself in abundant green. The rooms of the house flow seamlessly into the soothing green of the garden.' },
        { img: 'tuin-bar1402' },
        { cta: [ { label: 'All photos', href: '/en/photos/' }, { label: 'Email for availability', href: 'mailto:info@huizefrankendael.nl?subject=Festive%20room%20availability', kind: 'ghost' } ] },
      ],
    },
  },

  // ============================================================ Foto's / Photos
  {
    id: 'fotos', section: 'fotos', menu: null,
    path: { nl: '/nl/fotos/', en: '/en/photos/' },
    hero: 'luchtfoto-huis-en-tuin',
    title: { nl: 'Foto’s – Huize Frankendael', en: 'Photos – Huize Frankendael' },
    desc: {
      nl: 'Foto’s van Huize Frankendael: de salons, het koetshuis, de boardroom, de stijltuin, bruiloften, kunst en de keuken van Merkelbach.',
      en: 'Photos of Huize Frankendael: the salons, coach house, boardroom, formal garden, weddings, art and the Merkelbach kitchen.',
    },
    h1: { nl: 'Foto’s', en: 'Photos' },
    body: { nl: [ { gallery: true } ], en: [ { gallery: true } ] },
  },

  // ============================================================ Kunst / Art
  {
    id: 'kunst', section: 'kunst', menu: 'kunst',
    path: { nl: '/nl/kunst/', en: '/en/art/' },
    hero: 'frankendael-opening-wild-care-tame-neglect-06-hires',
    title: { nl: 'Kunst in Huize Frankendael – Frankendael Foundation', en: 'Art at Huize Frankendael – Frankendael Foundation' },
    desc: {
      nl: 'De Frankendael Foundation programmeert hedendaagse beeldende kunst in het 17e-eeuwse rijksmonument: tentoonstellingen, Art Dinners en een vaste collectie.',
      en: 'The Frankendael Foundation programmes contemporary visual art in the 17th-century national monument: exhibitions, Art Dinners and a permanent collection.',
    },
    h1: { nl: 'Kunst in Huize Frankendael', en: 'Art at Huize Frankendael' },
    body: {
      nl: [
        { h2: 'Hedendaagse kunst op een Amsterdamse buitenplaats' },
        { p: 'De Frankendael Foundation ontvangt publiek op de buitenplaats en stelt het huis open als tentoonstellingsruimte voor hedendaagse kunst. Geïnspireerd op de salon d’art laat de Foundation kunst resoneren in de samenleving, met tentoonstellingen, debatten, ontmoetingen en Art Dinners waar kunstenaars, bezoekers, verzamelaars en critici elkaar treffen.' },
        { p: 'In Huize Frankendael is te zien dat hedendaagse kunst en het 17e-eeuwse rijksmonument een inspirerende en spannende combinatie vormen. Momenteel is er geen tentoonstelling in huis; wil je zelf een tentoonstelling organiseren, mail dan naar [info@huizefrankendael.nl](mailto:info@huizefrankendael.nl).' },
        { h2: 'Bezoek' },
        { p: 'Tijdens het maandelijkse Open Huis — elke laatste zondag, gratis — bezoek je het huis en de kunst. Om 12.00 uur start een rondleiding. Alle praktische informatie staat bij [bezoek & rondleidingen](/nl/kunst/bezoek/).' },
        { openhouse: true },
        { h2: 'Archief' },
        { p: 'Sinds 2009 programmeerde de Foundation tientallen tentoonstellingen, soirees en Museumnachten. Blader door het [tentoonstellingsarchief](/nl/kunst/tentoonstellingen/).' },
        { cta: [ { label: 'Tentoonstellingsarchief', href: '/nl/kunst/tentoonstellingen/' }, { label: 'Over de Foundation', href: '/nl/kunst/over/', kind: 'ghost' } ] },
      ],
      en: [
        { h2: 'Contemporary art in an Amsterdam manorial estate' },
        { p: 'Frankendael Foundation welcomes the public to the estate and opens the house as an exhibition space for contemporary art. Inspired by the salon d’art, the Foundation makes art resonate throughout society by means of exhibitions, lively debates, networking and Art Dinners where artists, visitors, collectors and critics meet.' },
        { p: 'Huize Frankendael shows that contemporary art and the 17th-century national monument make an inspiring, exciting combination. There is currently no exhibition in the house; if you would like to organise one, email [info@huizefrankendael.nl](mailto:info@huizefrankendael.nl).' },
        { h2: 'Visiting' },
        { p: 'During the monthly Open House — every last Sunday, free of charge — you can visit the house and the art. A guided tour starts at noon. All practical information is under [your visit](/en/art/visiting/).' },
        { openhouse: true },
        { h2: 'Archive' },
        { p: 'Since 2009 the Foundation has programmed dozens of exhibitions, soirées and Museum Nights. Browse the [exhibition archive](/en/art/exhibitions/).' },
        { cta: [ { label: 'Exhibition archive', href: '/en/art/exhibitions/' }, { label: 'About the Foundation', href: '/en/art/about/', kind: 'ghost' } ] },
      ],
    },
  },

  {
    id: 'kunst-bezoek', section: 'kunst', menu: 'kunst',
    path: { nl: '/nl/kunst/bezoek/', en: '/en/art/visiting/' },
    hero: 'website-18',
    title: { nl: 'Bezoek en rondleidingen – Huize Frankendael', en: 'Your visit – Huize Frankendael' },
    desc: {
      nl: 'Bezoek Huize Frankendael tijdens het gratis Open Huis, elke laatste zondag 12.00–17.00 uur, met rondleiding om 12.00 uur. Groepsrondleidingen op afspraak.',
      en: 'Visit Huize Frankendael during the free Open House, every last Sunday 12–5 PM, with a guided tour at noon. Group tours by appointment.',
    },
    h1: { nl: 'Bezoek brengen aan Huize Frankendael', en: 'Visiting Huize Frankendael' },
    body: {
      nl: [
        { h2: 'Open Huis' },
        { p: 'Iedere laatste zondag van de maand, 12.00–17.00 uur, gratis. Ook het rechter koetshuis, waar [restaurant Merkelbach](https://restaurantmerkelbach.nl/) zit, is tentoonstellingsruimte.' },
        { openhouse: true },
        { h2: 'Rondleidingen' },
        { p: 'Iedere laatste zondag van de maand om 12.00 uur (gratis, maximaal 8 personen, aanmelden niet nodig). Tijdens de rondleiding hoor je over de geschiedenis van het huis, de tuin en de kunst — van vroeger en nu.' },
        { h2: 'Groepsrondleidingen' },
        { p: 'Een rondleiding voor je eigen groep, op een dag en tijdstip naar keuze, kost € 50,– per groep (maximaal 15 personen). Mail voor het boeken van een rondleiding — eventueel met lunch — naar [info@huizefrankendael.nl](mailto:info@huizefrankendael.nl).' },
        { h2: 'Goed om te weten' },
        { ul: [
          'In Huize Frankendael is geen lift; sommige ruimtes zijn alleen met de trap bereikbaar.',
          'Wegens privépartijen kunnen ruimtes bezet zijn. Bel vooraf [020 – 423 39 30](tel:+31204233930) om te vragen of de ruimtes beschikbaar zijn.',
        ] },
        { h2: 'Adres' },
        { p: 'Middenweg 72, 1097 BS Amsterdam — [bekijk de locatie op Google Maps](https://www.google.com/maps/place/Huize+Frankendael/@52.3511713,4.9313448,17z). Zie ook [route & parkeren](/nl/thuis/contact/route-parkeren/).' },
      ],
      en: [
        { h2: 'Open House' },
        { p: 'Every last Sunday of the month, 12–5 PM, free of charge. The right coach house, home to [restaurant Merkelbach](https://restaurantmerkelbach.nl/), is part of the exhibition space too.' },
        { openhouse: true },
        { h2: 'Guided tours' },
        { p: 'Every last Sunday of the month at noon (free, maximum 8 people, no registration needed). The tour covers the history of the house, the garden and the art — past and present.' },
        { h2: 'Group tours' },
        { p: 'A tour for your own group, on a day and time of your choosing, costs €50 per group (maximum 15 people). Email [info@huizefrankendael.nl](mailto:info@huizefrankendael.nl) to book a tour — with lunch, if you like.' },
        { h2: 'Good to know' },
        { ul: [
          'There is no lift in Huize Frankendael; some rooms can only be reached by stairs.',
          'Rooms may be occupied for private events. Call [+31 20 423 39 30](tel:+31204233930) in advance to check availability.',
        ] },
        { h2: 'Address' },
        { p: 'Middenweg 72, 1097 BS Amsterdam — [view the location on Google Maps](https://www.google.com/maps/place/Huize+Frankendael/@52.3511713,4.9313448,17z). See also [route & parking](/en/home/contact/parking-route/).' },
      ],
    },
  },

  {
    id: 'kunst-over', section: 'kunst', menu: 'kunst',
    path: { nl: '/nl/kunst/over/', en: '/en/art/about/' },
    hero: 'dieuwke-spaans-en-nick-oberthaler-61',
    title: { nl: 'Over de Frankendael Foundation', en: 'About the Frankendael Foundation' },
    desc: {
      nl: 'De Frankendael Foundation (ANBI, RSIN 820472657) programmeert hedendaagse kunst in Huize Frankendael, met de vaste collectie The Keys.',
      en: 'The Frankendael Foundation (ANBI, RSIN 820472657) programmes contemporary art at Huize Frankendael, with the permanent collection The Keys.',
    },
    h1: { nl: 'Over de Frankendael Foundation', en: 'About the Frankendael Foundation' },
    body: {
      nl: [
        { p: 'Huize Frankendael is de enige overgebleven 17e-eeuwse buitenplaats van Amsterdam. Het huis draagt veel geschiedenis in zich en is getuige geweest van vele veranderingen en verhalen in Amsterdam en Nederland: van republiek naar monarchie en van polder naar stad. Het huis behoort tot ons cultureel erfgoed. In Huize Frankendael en de tuin programmeert de Frankendael Foundation hedendaagse beeldende kunst: een plek waar met name jonge kunstenaars werk kunnen ontwikkelen en tonen, en curatoren tentoonstellingen kunnen maken.' },
        { h2: 'Collectie' },
        { p: 'Huize Frankendael heeft een vaste collectie, ‘The Keys’. In opdracht van de Frankendael Foundation maakten verschillende Nederlandse kunstenaars — onder wie Bas Louter, Saskia Noor van Imhoff en Erik Odijk — in 2010 werk geïnspireerd op de rijke geschiedenis van het huis en zijn bewoners: een reis door de historie met een eigentijdse blik. De muurtekening van Odijk is permanent te zien in de tuinkamer op de bovenverdieping; de andere werken worden met regelmaat uit het depot gehaald en opnieuw getoond. Parasite 22 van Dennis Feddersen (2011) is iedere dag te zien in [Restaurant Merkelbach](https://restaurantmerkelbach.nl/).' },
        { img: 'frankendael008', caption: 'Parasite 22, Dennis Feddersen (2011), in restaurant Merkelbach' },
        { h2: 'Stichting' },
        { p: 'Stichting Huize Frankendael / Frankendael Foundation is bij de Belastingdienst geregistreerd als algemeen nut beogende instelling (ANBI), RSIN 820472657.' },
        { p: 'Doelstelling (uit de statuten, november 2010): het vormen van een permanente basis voor, alswel het bevorderen, versterken en zichtbaar maken van, de uitwisseling tussen kunst, cultuur en wetenschap, het Nederlands culturele en maatschappelijke veld en het (Nederlandse) publiek. De stichting tracht haar doel onder meer te verwezenlijken door:' },
        { ul: [
          'het initiëren en organiseren van een programma van culturele activiteiten in de ruimste zin;',
          'het faciliteren, bevorderen en realiseren van bezoeken aan culturele evenementen;',
          'het bemiddelen in contacten tussen personen, culturele instellingen en organisaties;',
          'het creëren van gelegenheid tot presentaties van culturele uitingen.',
        ] },
        { p: 'De Foundation werkt volgens het bestuursmodel uit de Code Cultural Governance; bestuurders ontvangen geen beloning. Het bestuur bestaat uit Nynke de Haan, Joram Kraaijeveld, Caroline Vos en Bodo Groen. Beleidsplan: in overleg met het bestuur nuttig en zinvol besteden van subsidies, giften en inkomsten conform de doelstelling.' },
        { reports: true },
      ],
      en: [
        { p: 'Huize Frankendael is the only remaining 17th-century country estate of Amsterdam. The house carries a great deal of history and has witnessed many changes and stories in Amsterdam and the Netherlands: from republic to monarchy, from polder to city. It belongs to our cultural heritage. In Huize Frankendael and its garden, the Frankendael Foundation programmes contemporary visual art: a place where young artists in particular can develop and show work, and curators can make exhibitions.' },
        { h2: 'Collection' },
        { p: 'Huize Frankendael has a permanent collection, “The Keys”. Commissioned by the Frankendael Foundation, several Dutch artists — including Bas Louter, Saskia Noor van Imhoff and Erik Odijk — made work in 2010 inspired by the rich history of the house and its residents: a journey through history with a contemporary eye. Odijk’s wall drawing is on permanent display in the upstairs garden room; the other works are regularly brought out of storage and shown anew. Parasite 22 by Dennis Feddersen (2011) can be seen every day in [Restaurant Merkelbach](https://restaurantmerkelbach.nl/).' },
        { img: 'frankendael008', caption: 'Parasite 22, Dennis Feddersen (2011), in restaurant Merkelbach' },
        { h2: 'Foundation' },
        { p: 'Stichting Huize Frankendael / Frankendael Foundation is registered with the Dutch tax authority as a public benefit organisation (ANBI), RSIN 820472657.' },
        { p: 'Its objective (from the 2010 statutes): to form a permanent basis for — and to promote, strengthen and make visible — the exchange between art, culture and science, the Dutch cultural and social field, and the (Dutch) public. The foundation pursues this by, among other things:' },
        { ul: [
          'initiating and organising a programme of cultural activities in the broadest sense;',
          'facilitating, promoting and realising visits to cultural events;',
          'mediating contacts between people, cultural institutions and organisations;',
          'creating opportunities for the presentation of cultural expression.',
        ] },
        { p: 'The Foundation follows the governance model of the Code Cultural Governance; board members receive no remuneration. The board consists of Nynke de Haan, Joram Kraaijeveld, Caroline Vos and Bodo Groen. Policy: spending subsidies, gifts and income usefully and meaningfully, in line with the objective and in consultation with the board.' },
        { reports: true },
      ],
    },
  },

  {
    id: 'tentoonstellingen', section: 'kunst', menu: 'kunst',
    path: { nl: '/nl/kunst/tentoonstellingen/', en: '/en/art/exhibitions/' },
    hero: '12027206-1035288803185230-7053615541300625792-o',
    title: { nl: 'Tentoonstellingsarchief – Huize Frankendael', en: 'Exhibition archive – Huize Frankendael' },
    desc: {
      nl: 'Het tentoonstellingsarchief van de Frankendael Foundation, 2009–2018: van The Keys en Oh crisis! tot wild care, tame neglect en de collectie van Aernoud Bourdrez.',
      en: 'The exhibition archive of the Frankendael Foundation, 2009–2018: from The Keys and Oh crisis! to wild care, tame neglect and the Aernoud Bourdrez collection.',
    },
    h1: { nl: 'Tentoonstellingsarchief', en: 'Exhibition archive' },
    body: {
      nl: [
        { p: 'Van 2009 tot 2018 programmeerde de Frankendael Foundation tientallen tentoonstellingen, soirees, filmavonden en Museumnachten in Huize Frankendael. Dit archief documenteert die programmering. Wil je zelf een tentoonstelling organiseren in het huis, mail dan naar [info@huizefrankendael.nl](mailto:info@huizefrankendael.nl).' },
        { h2: 'Archief 2009 – 2018' },
        { exhibitions: true },
      ],
      en: [
        { p: 'From 2009 to 2018 the Frankendael Foundation programmed dozens of exhibitions, soirées, film nights and Museum Nights at Huize Frankendael. This archive documents that programme; descriptions are in Dutch. If you would like to organise an exhibition in the house, email [info@huizefrankendael.nl](mailto:info@huizefrankendael.nl).' },
        { h2: 'Archive 2009 – 2018' },
        { exhibitions: true },
      ],
    },
  },

  // ============================================================ Agenda / Calendar
  {
    id: 'agenda', section: 'agenda', menu: null,
    path: { nl: '/nl/agenda/', en: '/en/calendar/' },
    hero: 'tuin-bar1402',
    title: { nl: 'Agenda – Huize Frankendael', en: 'Calendar – Huize Frankendael' },
    desc: {
      nl: 'Open Huis elke laatste zondag van de maand met gratis rondleiding, kunst, en de nieuwsbrief en social media voor het actuele programma.',
      en: 'Open House every last Sunday of the month with a free guided tour, art, and the newsletter and social media for the current programme.',
    },
    h1: { nl: 'Agenda', en: 'Calendar' },
    body: {
      nl: [
        { h2: 'Open Huis — elke laatste zondag van de maand' },
        { p: 'Het huis is gratis te bezichtigen van 12.00 tot 17.00 uur, met om 12.00 uur een gratis rondleiding (maximaal 8 personen, aanmelden niet nodig). De eerstvolgende data:' },
        { openhouse: true },
        { h2: 'Kunst' },
        { p: 'Bekijk de [kunstpagina](/nl/kunst/) en het [tentoonstellingsarchief](/nl/kunst/tentoonstellingen/) van de Frankendael Foundation.' },
        { h2: 'Blijf op de hoogte' },
        { p: 'Volg [Huize Frankendael op Instagram](https://www.instagram.com/huize_frankendael/) en [Facebook](https://www.facebook.com/pages/Huize-Frankendael-restaurant-Merkelbach/177468635632918), of [Restaurant Merkelbach op Facebook](https://www.facebook.com/restaurantmerkelbach). [Aanmelden voor de nieuwsbrief](/nl/nieuwsbrief/) kan natuurlijk ook.' },
      ],
      en: [
        { h2: 'Open House — every last Sunday of the month' },
        { p: 'The house can be visited free of charge from 12 to 5 PM, with a free guided tour at noon (maximum 8 people, no registration needed). The next dates:' },
        { openhouse: true },
        { h2: 'Art' },
        { p: 'See the [art page](/en/art/) and the [exhibition archive](/en/art/exhibitions/) of the Frankendael Foundation.' },
        { h2: 'Stay up to date' },
        { p: 'Follow [Huize Frankendael on Instagram](https://www.instagram.com/huize_frankendael/) and [Facebook](https://www.facebook.com/pages/Huize-Frankendael-restaurant-Merkelbach/177468635632918), or [Restaurant Merkelbach on Facebook](https://www.facebook.com/restaurantmerkelbach). You can also [subscribe to the newsletter](/nl/nieuwsbrief/) (in Dutch).' },
      ],
    },
  },

  {
    id: 'nieuwsbrief', section: 'agenda', menu: null,
    path: { nl: '/nl/nieuwsbrief/', en: '/en/newsletter/' },
    hero: 'tuin-bloesem-bar1408',
    title: { nl: 'Nieuwsbrief – Huize Frankendael', en: 'Newsletter – Huize Frankendael' },
    desc: {
      nl: 'De nieuwsbrief van Huize Frankendael houdt je op de hoogte van de kunstagenda en activiteiten in huis. Bekijk eerdere edities of meld je aan.',
      en: 'The Huize Frankendael newsletter (in Dutch) keeps you up to date on the art programme and activities in the house. Browse earlier editions or subscribe.',
    },
    h1: { nl: 'Nieuwsbrief', en: 'Newsletter' },
    body: {
      nl: [
        { p: 'Via de nieuwsbrief brengen wij geïnteresseerden op de hoogte van de kunstagenda en andere activiteiten in huis.' },
        { cta: [ { label: 'Aanmelden per mail', href: 'mailto:info@huizefrankendael.nl?subject=Aanmelden%20nieuwsbrief' } ] },
        { h2: 'Eerdere edities' },
        { newsletterarchive: true },
      ],
      en: [
        { p: 'The newsletter (in Dutch) keeps subscribers informed about the art programme and other activities in the house.' },
        { cta: [ { label: 'Subscribe by email', href: 'mailto:info@huizefrankendael.nl?subject=Newsletter%20subscription' } ] },
        { h2: 'Earlier editions' },
        { newsletterarchive: true },
      ],
    },
  },

  // ============================================================ Contact
  {
    id: 'contact', section: 'thuis', menu: 'contact',
    path: { nl: '/nl/thuis/contact/', en: '/en/home/contact/' },
    hero: 'algemeen-routeparkeren',
    title: { nl: 'Contact en openingstijden – Huize Frankendael', en: 'Contact and opening hours – Huize Frankendael' },
    desc: {
      nl: 'Contact met Huize Frankendael: Middenweg 72 Amsterdam, 020 – 423 39 30. Openingstijden, privédiners, groepsaanvragen en reserveren bij Merkelbach.',
      en: 'Contact Huize Frankendael: Middenweg 72 Amsterdam, +31 20 423 39 30. Opening hours, private dinners, group enquiries and Merkelbach reservations.',
    },
    h1: { nl: 'Contact', en: 'Contact' },
    body: {
      nl: [
        { p: 'Het restaurant is elke dag open voor koffie & taart, à-la-cartelunch en een borrel; [lunchreserveringen graag online](https://bookings.zenchef.com/results?rid=371618). Een privédiner (vanaf 15 personen) in het huis organiseren kan ook — vraag informatie op per mail.' },
        { p: 'Voor vergaderruimtes en andere groepsaanvragen mail je (bij voorkeur) naar [info@huizefrankendael.nl](mailto:info@huizefrankendael.nl), of bel [020 – 423 39 30](tel:+31204233930) (ma t/m vr 9.00–17.00 uur).' },
        { h2: 'Openingstijden' },
        { hours: true },
        { note: 'In mei t/m september zijn er in de weekenden veel huwelijken in huis; de lunchtijden zijn dan vaak aangepast. Het online reserveringssysteem geeft dit automatisch aan.' },
        { h2: 'Adres' },
        { p: 'Huize Frankendael\nMiddenweg 72\n1097 BS Amsterdam\n[Bekijk de locatie op Google Maps](https://www.google.com/maps/place/Huize+Frankendael/@52.3511713,4.9313448,17z) of lees de [uitgebreide routebeschrijving](/nl/thuis/contact/route-parkeren/).' },
        { h2: 'Reserveren restaurant Merkelbach' },
        { p: 'Reserveren voor koffie, lunch of borrel doe je [online bij Merkelbach](https://bookings.zenchef.com/results?rid=371618). Let op: in het restaurant kun je alleen met pin of creditcard betalen.' },
        { h2: 'Bruidsreportage' },
        { p: 'Omdat er dagelijks groepen in huis zijn, is een losse bruidsreportage helaas niet mogelijk — tenzij je bij ons trouwt, dan kan het uiteraard wel.' },
        { h2: 'Team en vacatures' },
        { p: 'Vragen of opmerkingen? [Neem contact op met ons team](/nl/over/ons-team/). Werken bij Huize Frankendael? [Bekijk de vacatures](/nl/over/werken-bij-huize-frankendael/).' },
        { h2: 'Instagram & Facebook' },
        { p: '[Ga naar Instagram](https://www.instagram.com/huize_frankendael/) · [Ga naar Facebook](https://www.facebook.com/pages/Huize-Frankendael-restaurant-Merkelbach/177468635632918)' },
      ],
      en: [
        { p: 'The restaurant is open daily for coffee & cake, à la carte lunch and drinks; [please book lunch online](https://bookings.zenchef.com/results?rid=371618). We do not serve dinner, but a private dinner (from 15 people) in one of the rooms is possible — request information by email.' },
        { p: 'For meeting rooms and other group enquiries, preferably email [info@huizefrankendael.nl](mailto:info@huizefrankendael.nl), or call [+31 20 423 39 30](tel:+31204233930) (Mon–Fri 9 AM–5 PM).' },
        { h2: 'Opening hours' },
        { hours: true },
        { note: 'From May through September we host many weddings during the weekends; lunch hours are often adjusted on those days. The online reservation system will indicate this automatically.' },
        { h2: 'Address' },
        { p: 'Huize Frankendael\nMiddenweg 72\n1097 BS Amsterdam\n[View the location on Google Maps](https://www.google.com/maps/place/Huize+Frankendael/@52.3511713,4.9313448,17z) or read the [detailed route description](/en/home/contact/parking-route/).' },
        { h2: 'Reservations at restaurant Merkelbach' },
        { p: 'Book coffee, lunch or drinks [online at Merkelbach](https://bookings.zenchef.com/results?rid=371618). Please note: the restaurant only accepts debit or credit cards.' },
        { h2: 'Wedding photography' },
        { p: 'As we host groups in the house daily, stand-alone bridal photography is unfortunately not possible — unless you are getting married with us, in which case it naturally is.' },
        { h2: 'Team and vacancies' },
        { p: 'Questions or remarks? [Contact our team](/en/home/contact/our-team/). Working at Huize Frankendael? [See the vacancies](/en/home/contact/working-at-huize-frankendael/).' },
        { h2: 'Instagram & Facebook' },
        { p: '[Go to Instagram](https://www.instagram.com/huize_frankendael/) · [Go to Facebook](https://www.facebook.com/pages/Huize-Frankendael-restaurant-Merkelbach/177468635632918)' },
      ],
    },
  },

  {
    id: 'route', section: 'thuis', menu: 'contact',
    path: { nl: '/nl/thuis/contact/route-parkeren/', en: '/en/home/contact/parking-route/' },
    hero: 'algemeen-routeparkeren',
    title: { nl: 'Route & parkeren – Huize Frankendael', en: 'Route & parking – Huize Frankendael' },
    desc: {
      nl: 'Route naar Huize Frankendael, Middenweg 72 Amsterdam: parkeren in de VOMAR-garage of langs de straat, ov-verbindingen en routebeschrijvingen per auto.',
      en: 'Route to Huize Frankendael, Middenweg 72 Amsterdam: parking in the VOMAR garage or on the street, public transport connections and driving directions.',
    },
    h1: { nl: 'Route & parkeren', en: 'Route & parking' },
    body: {
      nl: [
        { p: 'Middenweg 72, 1097 BS Amsterdam — [bekijk de locatie op Google Maps](https://www.google.com/maps/place/Huize+Frankendael/@52.3511713,4.9313448,17z).' },
        { h2: 'Parkeren' },
        { parking: true },
        { h2: 'Openbaar vervoer' },
        { p: 'Huize Frankendael ligt in de Watergraafsmeer in Amsterdam-Oost en is goed bereikbaar met het openbaar vervoer:' },
        { ul: [
          'Vanaf station Amsterdam Muiderpoort: tram of bus richting Watergraafsmeer, halte Hugo de Vrieslaan.',
          'Vanaf station Amsterdam Amstel: stadsbussen en streekbussen over de Middenweg, halte Middenweg.',
          'Plan je reis actueel via [9292.nl](https://9292.nl/) of [GVB](https://www.gvb.nl/).',
        ] },
        { h2: 'Met de auto' },
        { h3: 'Vanuit richting Den Haag' },
        { p: 'Via de A4 richting Amsterdam. Voeg bij Amsterdam in op de A10 ringweg zuid. Neem afslag s113-Watergraafsmeer richting Diemen, ga rechtdoor (borden s113) en sla linksaf bij Middenweg/s113. Huize Frankendael ligt na 1,7 km op Middenweg 72, naast Restaurant De Kas.' },
        { h3: 'Vanuit richting Amersfoort' },
        { p: 'Via de A1/E231 richting Amsterdam. Neem bij Amsterdam de A10/E35 richting Ring Amsterdam (oost). Neem afslag s113-Watergraafsmeer richting Diemen, ga rechtdoor (borden s113) en sla rechtsaf bij Middenweg/s113. Huize Frankendael ligt na 1,7 km op Middenweg 72.' },
        { h3: 'Vanuit richting Utrecht' },
        { p: 'Via de A2/E35 richting Amsterdam. Neem de A10 richting Zaanstad. Neem afslag s113-Watergraafsmeer richting Diemen, ga rechtdoor (borden s113) en sla linksaf bij Middenweg/s113. Huize Frankendael ligt na 1,7 km op Middenweg 72.' },
        { h3: 'Vanuit richting Alkmaar' },
        { p: 'Via de A9 richting Amsterdam. Neem afslag E19/A4 richting Amsterdam en voeg in op de A10. Neem afslag s113-Watergraafsmeer richting Diemen, ga rechtdoor (borden s113) en sla linksaf bij Middenweg/s113. Huize Frankendael ligt na 1,7 km op Middenweg 72.' },
      ],
      en: [
        { p: 'Middenweg 72, 1097 BS Amsterdam — [view the location on Google Maps](https://www.google.com/maps/place/Huize+Frankendael/@52.3511713,4.9313448,17z).' },
        { h2: 'Parking' },
        { parking: true },
        { h2: 'Public transport' },
        { p: 'Huize Frankendael is located in the Watergraafsmeer area of Amsterdam-East and is easily reached by public transport:' },
        { ul: [
          'From Amsterdam Muiderpoort station: tram or bus towards Watergraafsmeer, stop Hugo de Vrieslaan.',
          'From Amsterdam Amstel station: city and regional buses along the Middenweg, stop Middenweg.',
          'Plan your journey via [9292.nl](https://9292.nl/en) or [GVB](https://www.gvb.nl/en).',
        ] },
        { h2: 'By car' },
        { h3: 'From the direction of The Hague' },
        { p: 'Via the A4 towards Amsterdam. At Amsterdam join the A10 ring road south. Take the s113-Watergraafsmeer exit towards Diemen, carry straight on (follow s113 signs) and turn left at Middenweg/s113. Huize Frankendael is at No. 72 Middenweg after approx. 1.7 km, next to Restaurant De Kas.' },
        { h3: 'From the direction of Amersfoort' },
        { p: 'Via the A1/E231 towards Amsterdam. At Amsterdam take the A10/E35 towards the Amsterdam ring (east). Take the s113-Watergraafsmeer exit towards Diemen, carry straight on (s113 signs) and turn right at Middenweg/s113. Huize Frankendael is at No. 72 Middenweg after approx. 1.7 km.' },
        { h3: 'From the direction of Utrecht' },
        { p: 'Via the A2/E35 towards Amsterdam. Take the A10 towards Zaanstad. Take the s113-Watergraafsmeer exit towards Diemen, carry straight on (s113 signs) and turn left at Middenweg/s113. Huize Frankendael is at No. 72 Middenweg after approx. 1.7 km.' },
        { h3: 'From the direction of Alkmaar' },
        { p: 'Via the A9 towards Amsterdam. Take the E19/A4 exit towards Amsterdam and join the A10. Take the s113-Watergraafsmeer exit towards Diemen, carry straight on (s113 signs) and turn left at Middenweg/s113. Huize Frankendael is at No. 72 Middenweg after approx. 1.7 km.' },
      ],
    },
  },

  // ============================================================ Recensies / Reviews
  {
    id: 'reviews', section: 'over', menu: null,
    path: { nl: '/nl/recensies/', en: '/en/reviews/' },
    hero: 'merkelbach-bar1484',
    title: { nl: 'Recensies – Huize Frankendael', en: 'Reviews – Huize Frankendael' },
    desc: {
      nl: 'Wat de pers schreef over Huize Frankendael en restaurant Merkelbach: Het Parool, De Telegraaf, Time Out Amsterdam, Misset Horeca en meer.',
      en: 'What the press wrote about Huize Frankendael and restaurant Merkelbach: Het Parool, De Telegraaf, Time Out Amsterdam, Misset Horeca and more.',
    },
    h1: { nl: 'Recensies', en: 'Reviews' },
    body: {
      nl: [
        { p: 'Een selectie van wat de pers over Huize Frankendael en restaurant Merkelbach schreef.' },
        { reviews: true },
      ],
      en: [
        { p: 'A selection of what the press wrote about Huize Frankendael and restaurant Merkelbach.' },
        { reviews: true },
      ],
    },
  },

  // ============================================================ Privacy
  {
    id: 'privacy', section: 'thuis', menu: null,
    path: { nl: '/nl/privacy/', en: '/en/privacy/' },
    hero: null,
    title: { nl: 'Privacy – Huize Frankendael', en: 'Privacy – Huize Frankendael' },
    desc: {
      nl: 'Hoe huizefrankendael.nl met je gegevens omgaat: geen cookies, geen trackers; alleen de gegevens die je zelf per mail of telefoon deelt.',
      en: 'How huizefrankendael.nl handles your data: no cookies, no trackers; only the information you share yourself by email or phone.',
    },
    h1: { nl: 'Privacy', en: 'Privacy' },
    body: {
      nl: [
        { p: 'Deze website is zo gebouwd dat er zo min mogelijk gegevens van je worden verwerkt.' },
        { h2: 'Wat deze website niet doet' },
        { ul: [
          'Geen cookies en geen vergelijkbare technieken; er is daarom ook geen cookiebanner.',
          'Geen analytics of andere trackers van derden.',
          'Geen contactformulieren: je neemt zelf contact op per e-mail of telefoon.',
        ] },
        { h2: 'Wat er wel gebeurt' },
        { ul: [
          'Als je mailt naar info@huizefrankendael.nl of belt, verwerken wij de gegevens die je zelf deelt (naam, contactgegevens, inhoud van je bericht) om je vraag te beantwoorden en een eventuele reservering of offerte af te handelen. [BEWAARTERMIJN INVULLEN — bijv. maximaal 2 jaar na het laatste contact.]',
          'De hostingpartij van deze website verwerkt beknopte technische logbestanden (zoals IP-adres en tijdstip) om de site veilig en bereikbaar te houden. [HOSTINGPARTIJ INVULLEN.]',
          'Reserveren bij restaurant Merkelbach gebeurt op de reserveringspagina van Zenchef, die pas opent nadat je erop klikt; daar geldt het privacybeleid van Zenchef en van het restaurant.',
          'Links naar externe diensten (Google Maps, Instagram, Facebook, de nieuwsbriefomgeving) openen pas nadat je erop klikt.',
        ] },
        { h2: 'Je rechten' },
        { p: 'Je hebt het recht op inzage, correctie en verwijdering van je persoonsgegevens. Neem daarvoor contact op via [info@huizefrankendael.nl](mailto:info@huizefrankendael.nl). Klachten kun je indienen bij de Autoriteit Persoonsgegevens.' },
        { h2: 'Verantwoordelijke' },
        { p: '[RECHTSPERSOON INVULLEN — bedrijfsnaam, KvK-nummer en vestigingsadres], Middenweg 72, 1097 BS Amsterdam, [info@huizefrankendael.nl](mailto:info@huizefrankendael.nl). Voor de kunstprogrammering: Stichting Huize Frankendael / Frankendael Foundation, RSIN 820472657.' },
      ],
      en: [
        { p: 'This website is built to process as little of your data as possible.' },
        { h2: 'What this website does not do' },
        { ul: [
          'No cookies or similar techniques; hence no cookie banner either.',
          'No analytics or other third-party trackers.',
          'No contact forms: you get in touch yourself by email or phone.',
        ] },
        { h2: 'What does happen' },
        { ul: [
          'If you email info@huizefrankendael.nl or call, we process the information you share yourself (name, contact details, the content of your message) to answer your enquiry and handle a reservation or proposal. [RETENTION PERIOD TO CONFIRM — e.g. at most 2 years after last contact.]',
          'The website’s hosting provider processes brief technical log files (such as IP address and time) to keep the site secure and available. [HOSTING PROVIDER TO CONFIRM.]',
          'Reservations at restaurant Merkelbach happen on the Zenchef reservation page, which only opens after you click it; Zenchef’s and the restaurant’s privacy policies apply there.',
          'Links to external services (Google Maps, Instagram, Facebook, the newsletter environment) only open after you click them.',
        ] },
        { h2: 'Your rights' },
        { p: 'You have the right to access, correct and delete your personal data. Contact [info@huizefrankendael.nl](mailto:info@huizefrankendael.nl) to do so. Complaints can be filed with the Dutch Data Protection Authority (Autoriteit Persoonsgegevens).' },
        { h2: 'Controller' },
        { p: '[LEGAL ENTITY TO CONFIRM — company name, Chamber of Commerce number and registered address], Middenweg 72, 1097 BS Amsterdam, [info@huizefrankendael.nl](mailto:info@huizefrankendael.nl). For the art programme: Stichting Huize Frankendael / Frankendael Foundation, RSIN 820472657.' },
      ],
    },
  },
];

// Hoofdmenu — dezelfde volgorde en sectiekleuren als de oude site.
export const nav = [
  { id: 'over', section: 'over', label: { nl: 'Over', en: 'About' }, href: { nl: '/nl/over/', en: '/en/about/' } },
  { id: 'fotos', section: 'fotos', label: { nl: 'Foto’s', en: 'Photos' }, href: { nl: '/nl/fotos/', en: '/en/photos/' } },
  { id: 'zakelijk', section: 'zakelijk', label: { nl: 'Zakelijk', en: 'Business' }, href: { nl: '/nl/zakelijk/', en: '/en/business/' } },
  { id: 'feestelijk', section: 'feestelijk', label: { nl: 'Feestelijk', en: 'Festivities' }, href: { nl: '/nl/feestelijk/', en: '/en/festivities/' } },
  { id: 'kunst', section: 'kunst', label: { nl: 'Kunst', en: 'Art' }, href: { nl: '/nl/kunst/', en: '/en/art/' } },
  { id: 'agenda', section: 'agenda', label: { nl: 'Agenda', en: 'Calendar' }, href: { nl: '/nl/agenda/', en: '/en/calendar/' } },
  { id: 'contact', section: 'thuis', label: { nl: 'Contact', en: 'Contact' }, href: { nl: '/nl/thuis/contact/', en: '/en/home/contact/' } },
];

// Submenu's per sectie (zoals de linkerkolom op de oude site).
export const submenus = {
  over: ['over', 'geschiedenis', 'team', 'werken', 'contact'],
  zakelijk: ['zakelijk', 'zakelijk-ruimtes', 'fotos', 'contact'],
  feestelijk: ['feestelijk', 'trouwen', 'feest-ruimtes', 'fotos', 'contact'],
  kunst: ['kunst', 'tentoonstellingen', 'kunst-bezoek', 'kunst-over', 'contact'],
  contact: ['contact', 'route', 'team', 'werken'],
};
